# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: mes_postgres
    restart: always
    environment:
      POSTGRES_DB: mes_db
      POSTGRES_USER: mes_user
      POSTGRES_PASSWORD: mes_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
